spring:
  datasource:
    url: jdbc:mysql://localhost:3306/research_management_db?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: tant
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB
      max-request-size: 2000MB
   
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: xyz.management.project.entity

  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰（数据库字段 project_name → 实体字段 projectName）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志（开发环境用）

file:
  project: /home/tanwen/project_management

